django_ajax/bookings/urls.py
from django.conf.urls import url

from django_ajax.bookings.views import list, list_date


urlpatterns = [
    url(r'^(?P<year>[\d]+)/(?P<month>[\d]+)/$', list_date, name='date'),
    url(r'$', list, name='list'),
]

django_ajax/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from django_ajax.bookings.views import BookingViewSet, home

router = routers.DefaultRouter()
router.register(r'bookings', BookingViewSet)

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^bookings/', include('django_ajax.bookings.urls', namespace='booking')),
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^auth/', include('rest_framework.urls', namespace='auth'))
]

django_ajax/bookings/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Booking(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='usuário')
    event = models.CharField('evento', max_length=128)
    date = models.DateField('data')
    created_on = models.DateTimeField('solicitado em', default=timezone.now)
    authorized = models.BooleanField('autorizado', default=False)

    class Meta:
        verbose_name = 'reserva'
        verbose_name_plural = 'reservas'
        ordering = ('-date',)

    def __str__(self):
        return self.event

django_ajax/bookings/views.py
from calendar import Calendar
from datetime import date, timedelta

from django.http import Http404
from django.shortcuts import render
from rest_framework.viewsets import ModelViewSet

from django_ajax.bookings.models import Booking
from django_ajax.bookings.serializer import BookingSerializer


class BookingViewSet(ModelViewSet):
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer


def home(request):
    return render(request, 'bookings/home.html')


def list(request):
    selected_date = date.today()
    return list_date(request, selected_date.year, selected_date.month)


def list_date(request, year, month):

    try:
        selected_date = date(int(year), int(month), 1)
    except ValueError:
        raise Http404

    context = {
        'selected_date': selected_date,
        'calendar': tuple(_calendar(selected_date)),
        'next': selected_date + timedelta(days=31),
        'previous': selected_date - timedelta(days=1)
    }

    return render(request, 'bookings/bookings_list.html', context)


def _calendar(selected_date):
    year, month = selected_date.year, selected_date.month
    filters = {'date__year':  year, 'date__month': month}
    bookings = {b.date: b for b in Booking.objects.filter(**filters)}
    calendar = Calendar(firstweekday=6)
    for week in calendar.monthdatescalendar(year, month):
        yield [(day, bookings.get(day)) for day in week]

django_ajax/bookings/templates/bookings/bookings_list.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booking</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </head>
  <body>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h1>Reservas</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <a href="{% url 'booking:date' year=previous.year month=previous.month %}">« Mês anterior</a>
      </div>
      <div class="col-md-5 text-right">
        <a href="{% url 'booking:date' year=next.year month=next.month %}">Próximo mês »</a>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">

        <table class="table table-bordered">

          <thead>
            <tr>
              <th colspan="7">{{ selected_date|date:"F" }} {{ selected_date.year }}</th>
            </tr>
            <tr>
              <th>Domingo</th>
              <th>Segunda</th>
              <th>Terça</th>
              <th>Quarta</th>
              <th>Quinta</th>
              <th>Sexta</th>
              <th>Sábado</th>
            </tr>
          </thead>

          <tbody>
            {% for week in calendar %}
            <tr>
              {% for day, booking in week %}
              <td
                {% if selected_date.month != day.month %}
                class ="other"
                {% else %}
                id="day_{{ day.day }}"
                {% endif %}
              >
                <strong>{{ day.day }}</strong>
                <br>
                {% if booking %}
                {{ booking.event }}
                ({{ booking.user.username }})
                {% else %}
                &nbsp;
                {% endif %}
              </td>
              {% endfor %}
            </tr>
            {% endfor %}
          </tbody>

        </table>

        {% if request.user.is_authenticated %}
        <h2>Faça sua reserva</h2>
        <form action="." method="post">

          <div class="form-group">
            <label for="event">Evento</label>
            <input class="form-control" type="text" id="event" name="event">
          </div>

          <div class="form-group">
            <label for="date">Data</label>
            <select class="form-control" name="date" id="date">
              {% for week in calendar %}
              {% for day, booking in week %}
              {% if not booking and selected_date.month == day.month %}
              <option value="X">{{ day }}</option>
              {% endif %}
              {% endfor %}
              {% endfor %}
            </select>
          </div>

          <button type="submit" class="btn btn-primary">Enviar</button>

        </form>
        {% endif %}


      </div><!-- end .col-md-10 -->
    </div><!-- end .row -->

  </body>
</html>

django_ajax/bookings/templates/bookings/home.html
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Booking</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  </head>
  <body>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">

        <h1>Endpoints</h1>

        <h2>Browser navigation</h2>

        <p>
          If user is authenticated (use
          <a href="http://localhost:8000/admin/">Django Admin</a>) it shows the
          form to make a new booking via AJAX (to be created during the
          Hangout).
        </p>

        <ul>
          <li>
            <code><a href="{% url 'booking:list' %}">/bookings/</a></code>:
            list all bookings from the current month
          </li>
          <li>
            <code>
              <a href="{% url 'booking:date' year=2016 month=12 %}">
                /bookings/&lt;year&gt;/&lt;month&gt;/
              </a>
            </code>
          (e.g. 
            <code>
              <a href="{% url 'booking:date' year=2016 month=12 %}">
                /bookings/2016/12/
              </a>
            </code>
          ): list all bookings from the
            current month  
        </ul>

        <h2>API</h2>
        <p>
          All endpoints requires authentication (use 
          <a href="http://localhost:8000/admin/">Django Admin</a>).
        </p>
        <ul>
          <li><code>GET /api/bookings/</code>: list all bookings</li>
          <li><code>POST /api/bookings/</code>: create new booking</li>
        </ul>
      </div><!-- end .col-md-10 -->
    </div><!-- end .row -->

  </body>
</html>